# Generated by Django 6.0.6 on 2026-06-24 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mi Empresa', max_length=200)),
                ('sla_warning_minutes', models.PositiveIntegerField(default=5, help_text='Minutos sin respuesta para marcar "Aviso".')),
                ('sla_critical_minutes', models.PositiveIntegerField(default=10, help_text='Minutos sin respuesta para marcar "Crítico".')),
                ('sla_escalate_minutes', models.PositiveIntegerField(default=15, help_text='Minutos sin respuesta para "Escalada" (dispara alertas).')),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('escalation_email', models.EmailField(blank=True, help_text='Correo que recibe la alerta cuando vence el SLA.', max_length=254)),
                ('alert_on_dashboard', models.BooleanField(default=True, help_text='Mostrar las escaladas en el dashboard del admin.')),
                ('auto_reassign', models.BooleanField(default=False, help_text='Reasignar automáticamente al agente libre con menos carga.')),
                ('relevance_filter_enabled', models.BooleanField(default=True, help_text='La IA no responde a mensajes irrelevantes o spam (acuses, emojis sueltos, etc.).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace (reglas de negocio)',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('agent', 'Agente')], default='agent', max_length=12)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('availability', models.CharField(choices=[('online', 'En línea'), ('busy', 'Ocupado'), ('away', 'Ausente')], default='away', max_length=10)),
                ('max_concurrent', models.PositiveIntegerField(default=5, help_text='Máximo de conversaciones activas simultáneas.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channels', models.ManyToManyField(blank=True, related_name='agents', to='conversations.channel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SLAAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Aviso'), ('critical', 'Crítico'), ('escalated', 'Escalada')], max_length=10)),
                ('wait_minutes', models.PositiveIntegerField(default=0)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
                ('acknowledged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='accounts.agent')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_alerts', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['resolved', '-triggered_at'], name='accounts_sl_resolve_7e3c06_idx')],
            },
        ),
    ]
