# Generated by Django 6.0.6 on 2026-06-24 23:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='max_custom_tools',
            field=models.PositiveIntegerField(default=10, help_text='Tope de herramientas personalizadas por el plan.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='tool_run_cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.002000'), help_text='Costo cobrado por cada ejecución de un webhook saliente.', max_digits=8),
        ),
        migrations.AddField(
            model_name='workspace',
            name='webhook_domain_allowlist',
            field=models.TextField(blank=True, help_text='Dominios permitidos para webhooks (coma-separado). Vacío = cualquiera (HTTPS, no privado).'),
        ),
    ]
