# Generated by Django 6.0.6 on 2026-06-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversations', '0002_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.agent'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('website', 'Website Widget')], max_length=20),
        ),
    ]
