# Generated by Django 6.0.6 on 2026-06-20 00:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('markup_multiplier', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Factor aplicado sobre el costo real de Anthropic', max_digits=6)),
                ('alert_threshold_usd', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Alerta cuando el saldo baje de este valor', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Account',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'Recarga'), ('usage', 'Consumo')], max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
