# Generated by Django 6.0.6 on 2026-06-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_agent_organization_alter_slaalert_organization_and_more'),
        ('billing', '0002_creditaccount_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.UniqueConstraint(fields=('organization',), name='uniq_creditaccount_org'),
        ),
    ]
