# Generated by Django 6.0.6 on 2026-06-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('doc_type', models.CharField(choices=[('overview', 'Descripción general'), ('product', 'Producto'), ('pricing', 'Precios'), ('faq', 'FAQ'), ('template', 'Plantilla')], default='overview', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
