# Generated by Django 6.0.6 on 2026-06-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('agent_name', models.CharField(default='Anna', max_length=100)),
                ('agent_gender', models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino'), ('neutral', 'Neutro')], default='female', max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('tone', models.CharField(blank=True, max_length=300)),
                ('identity_line', models.TextField(blank=True)),
                ('agent_description', models.TextField(blank=True)),
                ('behavior_rules', models.JSONField(default=list)),
                ('language_policy', models.CharField(choices=[('mirror', 'Espejo del cliente'), ('fixed', 'Idioma fijo')], default='mirror', max_length=50)),
                ('supported_languages', models.CharField(default='es, en', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='knowledgedoc',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='knowledgedoc',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='knowledgedoc',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgedoc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
