# Generated by Django 6.0.6 on 2026-06-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_aiconfig_and_doc_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='ai_api_key',
            field=models.TextField(blank=True),
        ),
    ]
