# Generated by Django 6.0.6 on 2026-06-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_aiconfig_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfig',
            name='ai_api_key',
        ),
    ]
