# Generated by Django 6.0.6 on 2026-06-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_remove_ai_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('archetype', models.CharField(choices=[('collect_data', 'Capturar datos'), ('tag_route', 'Etiquetar / enrutar'), ('canned_response', 'Respuesta guiada'), ('webhook', 'Webhook saliente')], max_length=20)),
                ('parameters', models.JSONField(default=list)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'En revisión'), ('approved', 'Aprobada')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomToolRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=42)),
                ('conversation_id', models.IntegerField(blank=True, null=True)),
                ('arguments', models.JSONField(default=dict)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('result', models.TextField(blank=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='knowledge.customtool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
