# Generated by Django 6.0.6 on 2026-06-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_agent_organization_alter_slaalert_organization_and_more'),
        ('integrations', '0002_integration_organization_quote_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
    ]
